name: Deploy to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Backend Dependencies
      run: |
        cd Backend
        pwd
        ls -al
        if [ -f package-lock.json ]; then
          npm ci
        else
          echo "package-lock.json NOT FOUND."
          exit 1
        fi

    - name: Install Frontend Dependencies
      run: |
        cd Frontend
        pwd
        ls -al
        if [ -f package-lock.json ]; then
          npm ci
        else
          echo "package-lock.json NOT FOUND."
          exit 1
        fi

    - name: Build Frontend
      run: |
        cd Frontend
        npm run build

    # Additional deployment steps...
