name: Deploy to AWS VM

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure Node.js version matches your project requirements
        cache: 'npm'

    - name: Install Backend Dependencies
      working-directory: ./Backend
      run: npm install

    - name: Install Frontend Dependencies
      working-directory: ./Frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./Frontend
      run: npm run build

    - name: Deploy to AWS VM
      env:
        SSH_KEY: |
          yg3h043uCkqanLawuY+sLpgKr/t4/obaxFkm2ADqrcQ # Your test SSH private key
        HOST: 16.171.171.132                         # Public IP of your AWS VM
        USER: ubuntu                                 # Username for the AWS VM
        BASE_URL: ${{ secrets.BASE_URL }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        # Save the SSH key to a file
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem

        # SSH into the AWS VM and deploy the project
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem $USER@$HOST << 'EOF'
          # Ensure backend directory exists, then update and restart
          mkdir -p ~/backend
          rsync -avz --delete ./Backend/ ~/backend
          cd ~/backend
          npm install

          # Write environment variables to the .env file
          echo "BASE_URL=$BASE_URL" > .env
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env

          # Restart backend service
          pm2 restart all || pm2 start src/index.js --name backend

          # Ensure frontend directory exists, then update and serve
          mkdir -p ~/frontend
          rsync -avz --delete ./Frontend/dist/ ~/frontend/dist
          pm2 serve ~/frontend/dist --name frontend --port 3000 --spa
        EOF

        # Remove the temporary SSH key
        rm ssh_key.pem
