- name: Deploy to AWS
  env:
    SSH_KEY: |
      yg3h043uCkqanLawuY+sLpgKr/t4/obaxFkm2ADqrcQ  # Your test SSH private key
    HOST: 16.171.171.132  # Your AWS VM public IP
    USER: ubuntu          # Your username for the AWS VM
  run: |
    # Save the SSH key to a file
    echo "$SSH_KEY" > ssh_key.pem
    chmod 600 ssh_key.pem

    # SSH into the AWS VM and deploy the project
    ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@16.171.171.132 << 'EOF'
      # Backend deployment
      mkdir -p ~/backend
      rsync -avz --delete ./Backend/ ~/backend
      cd ~/backend
      npm install
      pm2 restart all || pm2 start src/index.js --name backend

      # Frontend deployment
      mkdir -p ~/frontend
      rsync -avz --delete ./Frontend/dist/ ~/frontend/dist
      pm2 serve ~/frontend/dist --name frontend --port 3000 --spa
    EOF

    # Remove the temporary SSH key
    rm ssh_key.pem
