name: Deploy to AWS VM

on:
  push:
    branches:
      - main # Trigger only on main branch updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Directory Structure
      run: |
        echo "Listing all files in the workspace:"
        ls -R

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure Node.js version matches your project requirements
        cache: 'npm'

    - name: Find package-lock.json Files
      run: |
        echo "Finding all package-lock.json files:"
        find . -name "package-lock.json"

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./Backend
      run: |
        echo "Checking for Backend/package-lock.json..."
        test -f package-lock.json && npm ci || echo "package-lock.json not found"

    # Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./Frontend
      run: |
        echo "Checking for Frontend/package-lock.json..."
        test -f package-lock.json && npm ci || echo "package-lock.json not found"

    # Build Frontend
    - name: Build Frontend
      working-directory: ./Frontend
      run: npm run build

    # Deploy to AWS VM
    - name: Deploy to AWS VM
      env:
        SSH_KEY: |
          yg3h043uCkqanLawuY+sLpgKr/t4/obaxFkm2ADqrcQ
        HOST: 16.171.171.132
        USER: ubuntu
        BASE_URL: ${{ secrets.BASE_URL }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem

        ssh -o StrictHostKeyChecking=no -i ssh_key.pem $USER@$HOST << 'EOF'
          mkdir -p ~/backend
          rsync -avz --delete ./Backend/ ~/backend
          cd ~/backend
          npm install

          echo "BASE_URL=$BASE_URL" > .env
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env

          pm2 restart all || pm2 start src/index.js --name backend

          mkdir -p ~/frontend
          rsync -avz --delete ./Frontend/dist/ ~/frontend/dist
          pm2 serve ~/frontend/dist --name frontend --port 3000 --spa
        EOF

        rm ssh_key.pem
